### ISSUE TITLE
Export size?

### ISSUE THREAD

**Issue by ddubs13** [everything8215/ff6tools#1]
I'm attempting to edit an expanded, 4mb FFIII US ROM using FF6Tools, but it always cuts off at 3mb when I export it. Is there an way to fix that? (Accidentally asked this in the wrong github earlier)

**Comment by everything8215** [comment]
So you opened a previously expanded ROM and then saved it? I hadn't thought of that! I just uploaded a fix so that it will export the full ROM. Let me know if that works.

Depending on what you changed when you expanded your ROM (in FF3usME or w/e) some things may not work correctly in FF6Tools. But you should still be able to edit anything else.

**Comment by ddubs13** [comment]
Well, it keeps the ROM size, but behavior is still the same after editing: very buggy. To be specific, Terra's downward magitek armor sprite is messed up, and the game crashes upon loading a battle. It almost seems like it's shaving the data down to 3mb, and then re-expanding it, which wouldn't help.

It may be due to what I edited before attempting to use it, but all I'm doing is editing text strings.

**Comment by everything8215** [comment]
Hmmm, I'm not getting the same behavior when I test it. I'm guessing that the issue is related to whatever other tools you are using to make edits. If those edits were made in previously empty space, I think FF6Tools was overwriting them. I disabled this behavior so it might work now.

If you get the "Save ROM" dialog when saving, make sure to choose either "Truncate" or "Overwrite".

**Comment by ddubs13** [comment]
Thank you! My problem seems to be 100% solved!

Although, are you going to re-enable this behavior? Or are you going to alter it somehow? I also never got the "Save ROM" dialog when saving any of the time I've used this.

**Comment by everything8215** [comment]
Excellent! I'll leave it disabled. It just fills any empty space with padding (0xFF), but it's not really necessary. I don't think it's really feasible to get FF6Tools to be completely compatible with all the other tools out there but this makes it a little better at least.

The Save ROM dialog only appears if you expand something beyond its normal location in the ROM. Like for example if you add too many bytes to the map titles and they need to be relocated. If that happens, FF6Tools can attempt to automatically find an empty slot to put the data in. But in your case, some of the available empty space is already being used, so there would be nothing stopping it from overwriting your data.
