### ISSUE TITLE
well not a issue but how can i change a weapons graphic? and the script inside of it?

### ISSUE THREAD

**Issue by sus12345balls** [everything8215/ff6tools#11]

**Comment by everything8215** [comment]
If you're editing an FF6 ROM, go to Ability -> Attack Tilemap (3bpp). This allows you to edit the tilemap for all of the spell and weapon animations. If you want to change the graphics, you can import an image or a portion of an image using the little buttons in the right pane (where it says "Graphics"). When you import an image, the currently selected palette will get overwritten with the colors from the image, so make sure you have the right palette selected. FF6Tools can't currently edit animation scripts, but you can try to edit them manually with a hex editor. I made a dump of the animation scripts, available [here](https://www.ff6hacking.com/wiki/doku.php?id=ff3:ff3us:doc:game).

**Comment by sus12345balls** [comment]
srry for not commenting so long, had life problems I don't want to talk about
ANYWAYS thx for this for some reason I could find it weird but now I did thx so much

**Comment by sus12345balls** [comment]
What about adding new weapons, or adding new monsters or what about going past the 9999 damage health limit?

**Comment by everything8215** [comment]
Removing the damage cap requires an asm hack. Here is an existing hack that does this: https://www.romhacking.net/hacks/792/

Adding new weapons is difficult because all 256 item slots are already used. Going beyond 256 (like FF6 Advance) would require a major asm hack. Instead, you might want to try replacing existing weapons with new ones, which can be done with FF6Tools.

Adding new monsters is difficult for the same reason (there is a 384 monster cap). It might be possible to increase the cap to 512 with an asm hack, but this would be beyond the scope of FF6Tools. Again, it's much easier to replace existing monsters instead.

I'd recommend checking out the FF6Hacking forums and discord server. It's an excellent community of hackers with lots of knowledge about things beyond what can be done with FF6Tools.

**Comment by sus12345balls** [comment]
> https://www.romhacking.net/hacks/792/

ummm can you send me the discord link pls

**Comment by sus12345balls** [comment]
nvm found it thx alot man

**Comment by everything8215** [comment]
Great, I'm going to close this issue. If you need help with anything else feel free to send me a dm on discord.
