### ISSUE TITLE
Issue expanding tile layout size for field maps

### ISSUE THREAD

**Issue by snaphat** [everything8215/ff6tools#7]
Hi, I'm trying to expand the tile layout for maps that are 16x16 for a widescreen mod I am doing for FF6. I have all of the algorithmic logic written and working in the hack and noted some areas I need to expand/fix, etc.

Using FF6tools, when I try to expand a layers width or height above the original size, I get the behavior shown below and cannot actually edit the map as if it is double the width. Height expansion does the same thing. Is the base-tilelayout that is being loaded not increasing in size in-spite of specifying it for a given map (given that I know a given layout is shared between maps)? And if so is there a way to do this? Or is this just a bug?

![image](https://user-images.githubusercontent.com/5836001/117527700-f202e600-af9b-11eb-96c1-fb5c36eeb59c.png)

**Comment by snaphat** [comment]
Just for further reference, here's an example of what happens for 16x16 maps in the widescreen hack (it loops since there's not enough data), so that's why I am trying to expand the size of the chocobo stable for example.

![image](https://user-images.githubusercontent.com/5836001/117527871-1e6b3200-af9d-11eb-9d3f-56b3414dd529.png)

**Comment by everything8215** [comment]
Hi, yes this is something I’ve been meaning to deal with. I wouldn’t call it a bug, it’s just a feature I haven’t added yet. There are a couple things that need to happen to change the height or width of a map.

First, you need to change the height and width of each layer in map properties. It looks like you already did this. You also need to do the same thing for all maps that use the same tile layouts.

The next thing you need to do is change the size of the tile layout for each layer. For example, if you change the chocobo stable map from 16x16 to 32x16, you would need to change the tile layout size from 256 to 512. FF6Tools can’t do this right now but it’s a pretty quick fix. I’ll try to add it in the next couple of days.

The tile layouts are just a sequential array of bytes, they don’t know anything about height or width, so when you make these changes the rows of tiles are going to get interlaced like you’re seeing. For now you will have to manually rearrange the rows. Maybe I’ll add automatic deinterlacing at some point but it probably won’t be anytime soon.

One more thing, there’s not a lot of space in the ROM to expand the tile layouts, so you might need to have FF6Tools rearrange things or expand the ROM. It’s simpler if you don’t have to do that though. The tile layouts are compressed, and you can optimize the compression by filling long horizontal runs with a single tile. Take a look at the left edge of map 20 to see an example.

**Comment by snaphat** [comment]
Thanks for the quick and informative reply! I figured it was something like the tile layout needed to be changed.

Regarding the deinterlacing, that would actually be a very useful feature for me because I realize I'm going to have to expand some of the larger maps to space things out more in some cases because of things like this: https://github.com/snaphat/final_fantasy_vi_widescreen/issues/21, https://github.com/snaphat/final_fantasy_vi_widescreen/issues/18. Although perhaps there is an alternative I haven't thought of yet.

Speaking of that, is there a way to see a list of maps that use a given tile layout (if not in ff6tools, perhaps on the web somewhere?

Finally, regarding expanding tile layouts, I see what you mean after looking at map 20. However, I fear I will have to ultimately expand the rom. I updated some of the Vargas area so the edges aren't viewable in widescreen, but ff6tools told me I would need to expand it. I will go back and see if filling long horizontal rows with a single tile helps there (if possible in this case). The one good thing here is that the asm patch for supporting widescreen is separate from the map expansion patch so if someone wanted to utilize it for another hack, it should be possible to do.

**Comment by everything8215** [comment]
Okay, it's now possible to change the length of the layouts. There should be links in the map properties so that you can select the layouts (if there are no links, you'll need to re-open the ROM and select the built-in definition file from the list). With the layout selected, you should be able to change the length. Note that you will need to reload the map to see the changes (just select a different map and then reselect the map you're working on). I wanted to make the map redraw automatically, but I need to rework some things in the map editor first.

Once you've expanded the layout, you can use the "Interlace" button to fix any interlaced rows of tiles. There are 3 parameters for interlacing: word size, layers, and stride (these are just generic terms for the interlacing algorithm that aren't related to the map layers). I think you'll normally want to set the word size to the previous map width, and set layers to the previous map height. If you doubled or quadrupled the layout length, set stride to 2 or 4, respectively. When you hit okay, it will interlace the data. If you get the parameters wrong, you can hit undo and try again. And again, note that the map will not get redrawn automatically. You need to reload the map to see the changes.

I don't know of a listing of maps that use each tile layout, but someone might have compiled something on ff6hacking.com at some point.

Based on what you're planning, I think it might actually be feasible to widen all of the necessary layouts without expanding the ROM. The array optimization and compression algorithms built into FF6Tools are actually slightly more efficient than what the devs originally used, and since you are only adding horizontal rows of identical tiles, the overall compressed size might not increase. I tested it out by changing the chocobo stable maps to 32x16 and it seemed to work without expanding. Hit me up on the ff6hacking discord if you want any help getting things working.

I'm going to leave this issue open to remind me to make the map redraw automatically.

**Comment by snaphat** [comment]
Thanks for the feature! Using this, I was able to expand the chocobo stable, sabin's house, and duncan's house maps so far to 32x16. The trick to keep the compression working (for no rom expansion) is to move the actual houses to x coords 16-31. Additionally, when the house is on the right side of the map and x-wrap is enabled, the map will then center correctly (as opposed to when the house is located on the left side).

Once again, thanks for implementing these features! I don't believe my hack would be finishable without them
