### ISSUE TITLE
FFVI NPC indexing

### ISSUE THREAD

**Issue by AndrewDiMola** [everything8215/ff6tools#9]
Hey! Was wondering if there's an easy way to figure out which characters are assigned to the various NPC indexes without trial and error. Thanks!

This is in the context of editing Events with NPC objects.

**Comment by AndrewDiMola** [comment]
More context: Looks like Strago is NPC23 and Relm is NPC24 here, yet the index would have me think they're Moogles.
 
![image](https://user-images.githubusercontent.com/5179225/130121665-3eb7b7a5-9e12-4c4f-9b60-7c9284bbf222.png)

**Comment by everything8215** [comment]
Hi, thanks for pointing this out. The NPC numbers in the event script refer to the NPCs on the current map. The numbering was off by 16 though, so NPC 23 in the event script corresponded to NPC 7 on the map. I just fixed it so that they will both say NPC 7 now. You will need to reload your ROM for the change to take effect.  When you select an NPC on the map you can see its index in the dropdown at the top of the properties bar (i.e. "NPC Properties 7" when you select on the Strago NPC on this map).

btw, you can find lots of info about the ff6 event engine at ff6hacking.com and on the ff6 hacking discord.

**Comment by AndrewDiMola** [comment]
Thanks so much @everything8215! Will head over there!
